export const FETCH_RANDOM_QUOTE_REQUEST = 'FETCH_RANDOM_QUOTE_REQUEST'
export const FETCH_RANDOM_QUOTE_SUCCESS = 'FETCH_RANDOM_QUOTE_SUCCESS'
export const FETCH_RANDOM_QUOTE_FAILURE = 'FETCH_RANDOM_QUOTE_FAILURE'

export const FETCH_FAV_QUOTES_REQUEST = 'FETCH_FAV_QUOTES_REQUEST'
export const FETCH_FAV_QUOTES_SUCCESS = 'FETCH_FAV_QUOTES_SUCCESS'
export const FETCH_FAV_QUOTES_FAILURE = 'FETCH_FAV_QUOTES_FAILURE'

export const TOGGLE_AUTHOR = 'TOGGLE_AUTHOR'
export const TOGGLE_TAG = 'TOGGLE_TAG'

export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE'
export const REMOVE_FAV_QUOTE = 'REMOVE_FAV_QUOTE'

export const FETCH_SEARCH_QUOTES_REQUEST = 'FETCH_SEARCH_QUOTES_REQUEST'
export const FETCH_SEARCH_QUOTES_SUCCESS = 'FETCH_SEARCH_QUOTES_SUCCESS'
export const FETCH_SEARCH_QUOTES_FAILURE = 'FETCH_SEARCH_QUOTES_FAILURE'
export const CHANGE_SEARCH_KEY = 'CHANGE_SEARCH_KEY'
